# Generated by Django 2.2.4 on 2021-05-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
